import { CalendarDate } from "@internationalized/date";
import {
  newCheckItem,
  newGroupingItem,
  newPanelItem,
  newProjectInstance,
  newProjectItem,
  newTodoItem,
  type PanelItem,
  type ProjectItem,
} from "./model";

// The guest demo is server-rendered and then hydrated on the client, so its
// entity ids must be identical on both sides — `crypto.randomUUID` would differ
// between the two renders and break hydration. Assign deterministic,
// position-based ids prefixed `guest-`; they're rewritten to fresh UUIDs at
// sign-up (see materializeGuestIds) so different guests never collide on the
// global primary key.
export const GUEST_ID_PREFIX = "guest-";

const assignGuestIds = (projects: ProjectItem[]): ProjectItem[] => {
  projects.forEach((proj, pi) => {
    proj.id = `${GUEST_ID_PREFIX}p${pi}`;
    proj.rows.forEach((row, ri) => {
      row.id = `${proj.id}-r${ri}`;
      if ("checks" in row) {
        row.checks.forEach((check, ci) => {
          check.id = `${row.id}-c${ci}`;
        });
      }
    });
  });
  return projects;
};

export const freshMockProjects = (): ProjectItem[] =>
  assignGuestIds([
    newProjectItem({
      name: "Click Here & Drag There",
      note: "Things you can try 🎉",
      rows: [
        newTodoItem({
          title: "Expand, collapse, adjust the side bar",
          note: "which is only enabled on the first panel; click the hover-to-appear drag handle to toggle visibility",
        }),
        newGroupingItem({ label: "Double-click a heading to edit" }),
        newTodoItem({
          title: "Double-click a todo to expand",
          note: "click on the top or bottom margin to collapse it",
          checks: [
            newCheckItem({ text: "Each todo can have its own checklist" }),
            newCheckItem({ text: "Checks are reorderable by dragging the right-top handle" }),
            newCheckItem({
              text: "Use `delete` and `return` keys to intuitively split, merge, create, or delete checks",
            }),
          ],
        }),
        newTodoItem({ title: "Double-click a project row at the sidebar to edit" }),
        newGroupingItem({ label: "Drag things" }),
        newTodoItem({ title: "Drag to adjust the side bar" }),
        newTodoItem({
          title: "Drag multiple rows from a project",
          note: "drop them into a target project at the side bar or at another panel",
          checks: [
            newCheckItem({
              text: "Or drop todos into Archive (only completed todos), Trash, or Inbox",
            }),
            newCheckItem({ text: "Or just reorder them" }),
          ],
        }),
        newTodoItem({
          title: "Drag multiple project rows from the side bar",
          checks: [
            newCheckItem({ text: "Reorder them" }),
            newCheckItem({ text: "Move them to Trash or Archive" }),
          ],
        }),
        newTodoItem({ title: "Resize panels and adjust spacings" }),
        newGroupingItem({ label: "Use keyboard" }),
        newTodoItem({
          title: "Cmd/Ctrl-click on rows to multi-select",
          checks: [
            newCheckItem({ text: "Shift-click to select a range of rows" }),
            newCheckItem({
              text: "Cmd/Ctrl + A to select all rows under a heading or in a project",
            }),
          ],
        }),
        newTodoItem({
          title: "Arrow up/down key to navigate row-selection",
          note: "use Arrow left/right key to switch focus between panels",
        }),
        newTodoItem({ title: "Space key to create a todo" }),
        newTodoItem({
          title: "Enter key to expand a todo",
          note: "and to collapse it when focused on the title; also can use Escape key to collapse the todo",
        }),
        newTodoItem({
          title: "Delete key to move todos to Trash",
          note: "and delete headings",
        }),
        newTodoItem({
          title: "Cmd/Ctrl + Z to undo todo moves",
          note: "Cmd/Ctrl + Shift + Z (or Ctrl + Y) to redo — check moves undo and redo too",
          checks: [
            newCheckItem({ text: "Undo drag moves, reorders, and deletes to Trash" }),
            newCheckItem({ text: "Also undo check reorders and deletes — try it right here" }),
            newCheckItem({ text: "Editing or creating rows starts a fresh history" }),
          ],
        }),
        newGroupingItem({ label: "More" }),
        newTodoItem({
          title: "Sign up an account to persist your data",
          note: "and layout preference",
        }),
      ],
    }),
    newProjectItem({
      name: "US Presidents",
      note: "All 47 presidents",
      rows: [
        newGroupingItem({ label: "Founding Era" }),
        newTodoItem({
          title: "1. George Washington",
          note: "1789–1797 · Set two-term precedent, commanded Revolutionary forces",
          planned: new CalendarDate(1732, 2, 22),
          status: "complete",
          checks: [
            newCheckItem({ text: "Commanded Continental Army", ticked: true }),
            newCheckItem({ text: "Chaired Constitutional Convention", ticked: true }),
            newCheckItem({ text: "Declined third term", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "2. John Adams",
          note: "1797–1801 · First to live in the White House; avoided war with France",
          planned: new CalendarDate(1735, 10, 30),
          status: "complete",
          checks: [
            newCheckItem({ text: "Signed Alien & Sedition Acts", ticked: true }),
            newCheckItem({ text: "Kept US out of Quasi-War with France", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "3. Thomas Jefferson",
          note: "1801–1809 · Author of Declaration of Independence; Louisiana Purchase doubled US territory",
          planned: new CalendarDate(1743, 4, 13),
          status: "complete",
          checks: [
            newCheckItem({ text: "Authored Declaration of Independence", ticked: true }),
            newCheckItem({ text: "Louisiana Purchase (1803)", ticked: true }),
            newCheckItem({ text: "Founded University of Virginia", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "4. James Madison",
          note: "1809–1817 · Father of the Constitution; led US through War of 1812",
          planned: new CalendarDate(1751, 3, 16),
          status: "complete",
          checks: [
            newCheckItem({ text: "Drafted US Constitution", ticked: true }),
            newCheckItem({ text: "Co-wrote Federalist Papers", ticked: true }),
            newCheckItem({ text: "War of 1812", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "5. James Monroe",
          note: "1817–1825 · Era of Good Feelings; Monroe Doctrine warned Europe off Americas",
          planned: new CalendarDate(1758, 4, 28),
          status: "complete",
          checks: [
            newCheckItem({ text: "Monroe Doctrine (1823)", ticked: true }),
            newCheckItem({ text: "Missouri Compromise", ticked: true }),
          ],
        }),
        newGroupingItem({ label: "19th Century" }),
        newTodoItem({
          title: "6. John Quincy Adams",
          note: "1825–1829 · Son of #2; strong advocate for internal improvements and science",
          planned: new CalendarDate(1767, 7, 11),
          status: "complete",
          checks: [
            newCheckItem({ text: "Promoted national university and observatory", ticked: true }),
            newCheckItem({ text: "Later served in Congress post-presidency", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "7. Andrew Jackson",
          note: "1829–1837 · Populist hero; Indian Removal Act displaced thousands",
          planned: new CalendarDate(1767, 3, 15),
          status: "complete",
          checks: [
            newCheckItem({ text: "Indian Removal Act (1830)", ticked: true }),
            newCheckItem({ text: "Vetoed Second Bank of the US", ticked: true }),
            newCheckItem({ text: "Survived assassination attempt", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "8. Martin Van Buren",
          note: "1837–1841 · Panic of 1837 defined his term; founded Democratic Party machinery",
          planned: new CalendarDate(1782, 12, 5),
          status: "complete",
          checks: [
            newCheckItem({ text: "Panic of 1837 financial crisis", ticked: true }),
            newCheckItem({ text: "Established independent treasury", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "9. William Henry Harrison",
          note: "1841 · Shortest presidency — died of pneumonia 31 days after inauguration",
          planned: new CalendarDate(1773, 2, 9),
          status: "complete",
          checks: [
            newCheckItem({ text: "Longest inaugural address in history", ticked: true }),
            newCheckItem({ text: "Died 31 days into office", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "10. John Tyler",
          note: "1841–1845 · First VP to assume presidency; expelled from his own party",
          planned: new CalendarDate(1790, 3, 29),
          status: "complete",
          checks: [
            newCheckItem({ text: "Annexed Texas", ticked: true }),
            newCheckItem({ text: "Vetoed Whig legislation; party expelled him", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "11. James K. Polk",
          note: "1845–1849 · Expanded US by a third via Mexican-American War and Oregon Treaty",
          planned: new CalendarDate(1795, 11, 2),
          status: "complete",
          checks: [
            newCheckItem({ text: "Oregon Territory secured from Britain", ticked: true }),
            newCheckItem({ text: "Mexican-American War", ticked: true }),
            newCheckItem({ text: "Kept all four campaign promises", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "12. Zachary Taylor",
          note: "1849–1850 · War hero who died 16 months in; opposed spread of slavery",
          planned: new CalendarDate(1784, 11, 24),
          status: "complete",
          checks: [
            newCheckItem({ text: "Hero of Mexican-American War", ticked: true }),
            newCheckItem({ text: "Died in office (1850)", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "13. Millard Fillmore",
          note: "1850–1853 · Signed Compromise of 1850 including Fugitive Slave Act",
          planned: new CalendarDate(1800, 1, 7),
          status: "complete",
          checks: [
            newCheckItem({ text: "Signed Compromise of 1850", ticked: true }),
            newCheckItem({ text: "Opened Japan to US trade", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "14. Franklin Pierce",
          note: "1853–1857 · Kansas-Nebraska Act inflamed sectional tensions over slavery",
          planned: new CalendarDate(1804, 11, 23),
          status: "complete",
          checks: [
            newCheckItem({ text: "Kansas-Nebraska Act (1854)", ticked: true }),
            newCheckItem({ text: "Gadsden Purchase completed southern border", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "15. James Buchanan",
          note: "1857–1861 · Widely considered worst president; failed to prevent secession",
          planned: new CalendarDate(1791, 4, 23),
          status: "complete",
          checks: [
            newCheckItem({ text: "Dred Scott decision on his watch", ticked: true }),
            newCheckItem({ text: "Did not act against seceding states", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "16. Abraham Lincoln",
          note: "1861–1865 · Preserved the Union; issued Emancipation Proclamation; assassinated",
          planned: new CalendarDate(1809, 2, 12),
          status: "complete",
          checks: [
            newCheckItem({ text: "Led Union through Civil War", ticked: true }),
            newCheckItem({ text: "Emancipation Proclamation (1863)", ticked: true }),
            newCheckItem({ text: "Assassinated by John Wilkes Booth", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "17. Andrew Johnson",
          note: "1865–1869 · Lenient Reconstruction plan; first president impeached by the House",
          planned: new CalendarDate(1808, 12, 29),
          status: "complete",
          checks: [
            newCheckItem({ text: "Purchased Alaska from Russia", ticked: true }),
            newCheckItem({ text: "Impeached by House; acquitted by Senate", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "18. Ulysses S. Grant",
          note: "1869–1877 · Civil War hero; administration marred by widespread corruption",
          planned: new CalendarDate(1822, 4, 27),
          status: "complete",
          checks: [
            newCheckItem({ text: "Ratified 15th Amendment", ticked: true }),
            newCheckItem({ text: "Crédit Mobilier and Whiskey Ring scandals", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "19. Rutherford B. Hayes",
          note: "1877–1881 · Disputed election ended Reconstruction; pushed civil service reform",
          planned: new CalendarDate(1822, 10, 4),
          status: "complete",
          checks: [
            newCheckItem({ text: "Ended Reconstruction by withdrawing troops", ticked: true }),
            newCheckItem({ text: "Fought for civil service reform", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "20. James A. Garfield",
          note: "1881 · Assassinated 200 days in; championed education and civil rights",
          planned: new CalendarDate(1831, 11, 19),
          status: "complete",
          checks: [
            newCheckItem({ text: "Shot by disappointed office-seeker", ticked: true }),
            newCheckItem({ text: "Died 79 days after being shot", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "21. Chester A. Arthur",
          note: "1881–1885 · Surprised critics with honest governance; Pendleton Civil Service Act",
          planned: new CalendarDate(1829, 10, 5),
          status: "complete",
          checks: [
            newCheckItem({ text: "Pendleton Civil Service Reform Act", ticked: true }),
            newCheckItem({ text: "Modernized US Navy", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "22. Grover Cleveland",
          note: "1885–1889 · First Democrat after Civil War; known for vetoing pork-barrel bills",
          planned: new CalendarDate(1837, 3, 18),
          status: "complete",
          checks: [
            newCheckItem({ text: "Vetoed hundreds of private pension bills", ticked: true }),
            newCheckItem({ text: "Interstate Commerce Act signed", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "23. Benjamin Harrison",
          note: "1889–1893 · Six states admitted to union; Sherman Antitrust Act passed",
          planned: new CalendarDate(1833, 8, 20),
          status: "complete",
          checks: [
            newCheckItem({ text: "Sherman Antitrust Act (1890)", ticked: true }),
            newCheckItem({ text: "Six states admitted to the Union", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "24. Grover Cleveland",
          note: "1893–1897 · Only president to serve two non-consecutive terms",
          planned: new CalendarDate(1837, 3, 18),
          status: "complete",
          checks: [
            newCheckItem({ text: "Only non-consecutive two-term president", ticked: true }),
            newCheckItem({ text: "Repealed Silver Purchase Act amid depression", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "25. William McKinley",
          note: "1897–1901 · Spanish-American War made US a global power; assassinated",
          planned: new CalendarDate(1843, 1, 29),
          status: "complete",
          checks: [
            newCheckItem({ text: "Spanish-American War (1898)", ticked: true }),
            newCheckItem({ text: "Annexed Hawaii, Philippines, Puerto Rico", ticked: true }),
            newCheckItem({ text: "Assassinated; TR succeeded him", ticked: true }),
          ],
        }),
        newGroupingItem({ label: "Early 20th Century" }),
        newTodoItem({
          title: "26. Theodore Roosevelt",
          note: "1901–1909 · Trust-busting, conservation, and Big Stick foreign policy",
          planned: new CalendarDate(1858, 10, 27),
          status: "complete",
          checks: [
            newCheckItem({ text: "Busted railroad and oil trusts", ticked: true }),
            newCheckItem({ text: "Created 150 national forests and parks", ticked: true }),
            newCheckItem({
              text: "Nobel Peace Prize for mediating Russo-Japanese War",
              ticked: true,
            }),
          ],
        }),
        newTodoItem({
          title: "27. William Howard Taft",
          note: "1909–1913 · More antitrust suits than TR; later became Chief Justice",
          planned: new CalendarDate(1857, 9, 15),
          status: "complete",
          checks: [
            newCheckItem({ text: "Filed more antitrust suits than Roosevelt", ticked: true }),
            newCheckItem({
              text: "Only person to be both President and Chief Justice",
              ticked: true,
            }),
          ],
        }),
        newTodoItem({
          title: "28. Woodrow Wilson",
          note: "1913–1921 · Led US through WWI; championed League of Nations (which Senate rejected)",
          planned: new CalendarDate(1856, 12, 28),
          status: "complete",
          checks: [
            newCheckItem({ text: "Federal Reserve Act (1913)", ticked: true }),
            newCheckItem({ text: "Led US into World War I", ticked: true }),
            newCheckItem({ text: "Proposed League of Nations", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "29. Warren G. Harding",
          note: "1921–1923 · Teapot Dome scandal; died in office",
          planned: new CalendarDate(1865, 11, 2),
          status: "complete",
          checks: [
            newCheckItem({ text: "Teapot Dome oil bribery scandal", ticked: true }),
            newCheckItem({ text: "Died in office (1923)", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "30. Calvin Coolidge",
          note: "1923–1929 · 'Silent Cal' presided over Roaring Twenties prosperity",
          planned: new CalendarDate(1872, 7, 4),
          status: "complete",
          checks: [
            newCheckItem({ text: "Reduced national debt and taxes", ticked: true }),
            newCheckItem({ text: "Declined to seek re-election in 1928", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "31. Herbert Hoover",
          note: "1929–1933 · Great Depression began on his watch; opposed direct federal relief",
          planned: new CalendarDate(1874, 8, 10),
          status: "complete",
          checks: [
            newCheckItem({ text: "Stock market crash October 1929", ticked: true }),
            newCheckItem({ text: "Smoot-Hawley Tariff deepened Depression", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "32. Franklin D. Roosevelt",
          note: "1933–1945 · New Deal, WWII; only president elected four times",
          planned: new CalendarDate(1882, 1, 30),
          status: "complete",
          checks: [
            newCheckItem({ text: "New Deal programs combated Depression", ticked: true }),
            newCheckItem({ text: "Led US through World War II", ticked: true }),
            newCheckItem({ text: "Elected four times; died in office", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "33. Harry S. Truman",
          note: "1945–1953 · Dropped atomic bombs; Marshall Plan rebuilt Europe; Korean War",
          planned: new CalendarDate(1884, 5, 8),
          status: "complete",
          checks: [
            newCheckItem({ text: "Authorized atomic bombs on Japan", ticked: true }),
            newCheckItem({ text: "Marshall Plan to rebuild Europe", ticked: true }),
            newCheckItem({ text: "Desegregated US military", ticked: true }),
          ],
        }),
        newGroupingItem({ label: "Modern Era" }),
        newTodoItem({
          title: "34. Dwight D. Eisenhower",
          note: "1953–1961 · WWII Supreme Commander; Interstate Highway System; warned of military-industrial complex",
          planned: new CalendarDate(1890, 10, 14),
          status: "complete",
          checks: [
            newCheckItem({ text: "Korean War armistice", ticked: true }),
            newCheckItem({ text: "Interstate Highway System", ticked: true }),
            newCheckItem({ text: "Sent troops to enforce school desegregation", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "35. John F. Kennedy",
          note: "1961–1963 · Moon mission, Cuban Missile Crisis; assassinated in Dallas",
          planned: new CalendarDate(1917, 5, 29),
          status: "complete",
          checks: [
            newCheckItem({ text: "Cuban Missile Crisis (1962)", ticked: true }),
            newCheckItem({ text: "Launched Apollo space program", ticked: true }),
            newCheckItem({ text: "Assassinated in Dallas (1963)", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "36. Lyndon B. Johnson",
          note: "1963–1969 · Great Society; Civil Rights Act; escalated Vietnam War",
          planned: new CalendarDate(1908, 8, 27),
          status: "complete",
          checks: [
            newCheckItem({ text: "Civil Rights Act (1964)", ticked: true }),
            newCheckItem({ text: "Medicare and Medicaid established", ticked: true }),
            newCheckItem({ text: "Escalated Vietnam; declined re-election bid", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "37. Richard Nixon",
          note: "1969–1974 · Opened China; EPA created; resigned over Watergate",
          planned: new CalendarDate(1913, 1, 9),
          status: "complete",
          checks: [
            newCheckItem({ text: "Opened diplomatic relations with China", ticked: true }),
            newCheckItem({ text: "Founded EPA; Clean Air Act", ticked: true }),
            newCheckItem({ text: "Resigned over Watergate scandal", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "38. Gerald Ford",
          note: "1974–1977 · Only president never elected VP or President; pardoned Nixon",
          planned: new CalendarDate(1913, 7, 14),
          status: "complete",
          checks: [
            newCheckItem({ text: "Pardoned Richard Nixon", ticked: true }),
            newCheckItem({ text: "Never elected to national office", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "39. Jimmy Carter",
          note: "1977–1981 · Camp David Accords; Iran hostage crisis ended presidency",
          planned: new CalendarDate(1924, 10, 1),
          status: "complete",
          checks: [
            newCheckItem({ text: "Camp David Accords (Egypt-Israel peace)", ticked: true }),
            newCheckItem({ text: "Iran hostage crisis lasted 444 days", ticked: true }),
            newCheckItem({ text: "Nobel Peace Prize (2002, post-presidency)", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "40. Ronald Reagan",
          note: "1981–1989 · Reaganomics, Cold War endgame, Iran-Contra affair",
          planned: new CalendarDate(1911, 2, 6),
          status: "complete",
          checks: [
            newCheckItem({ text: "Survived assassination attempt (1981)", ticked: true }),
            newCheckItem({ text: "Tax cuts and deregulation (Reaganomics)", ticked: true }),
            newCheckItem({ text: "Cold War end; Berlin Wall fell shortly after", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "41. George H.W. Bush",
          note: "1989–1993 · Gulf War coalition; oversaw Soviet collapse",
          planned: new CalendarDate(1924, 6, 12),
          status: "complete",
          checks: [
            newCheckItem({ text: "Gulf War: liberated Kuwait (1991)", ticked: true }),
            newCheckItem({ text: "Oversaw dissolution of Soviet Union", ticked: true }),
            newCheckItem({ text: "Americans with Disabilities Act signed", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "42. Bill Clinton",
          note: "1993–2001 · Economic boom; NAFTA; impeached over Lewinsky affair",
          planned: new CalendarDate(1946, 8, 19),
          status: "complete",
          checks: [
            newCheckItem({ text: "Budget surplus achieved", ticked: true }),
            newCheckItem({ text: "NAFTA signed", ticked: true }),
            newCheckItem({ text: "Impeached; acquitted by Senate", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "43. George W. Bush",
          note: "2001–2009 · 9/11 response; wars in Afghanistan and Iraq; 2008 financial crisis",
          planned: new CalendarDate(1946, 7, 6),
          status: "complete",
          checks: [
            newCheckItem({ text: "Responded to 9/11 attacks", ticked: true }),
            newCheckItem({ text: "Wars in Afghanistan and Iraq", ticked: true }),
            newCheckItem({ text: "2008 financial crisis and bailout", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "44. Barack Obama",
          note: "2009–2017 · First Black president; ACA; killed bin Laden; Nobel Peace Prize",
          planned: new CalendarDate(1961, 8, 4),
          status: "complete",
          checks: [
            newCheckItem({ text: "Affordable Care Act (2010)", ticked: true }),
            newCheckItem({ text: "Authorized raid that killed bin Laden", ticked: true }),
            newCheckItem({ text: "Nobel Peace Prize (2009)", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "45. Donald Trump",
          note: "2017–2021 · Tax cuts; impeached twice; COVID-19 pandemic",
          planned: new CalendarDate(1946, 6, 14),
          status: "complete",
          checks: [
            newCheckItem({ text: "Tax Cuts and Jobs Act (2017)", ticked: true }),
            newCheckItem({ text: "Impeached twice by the House", ticked: true }),
            newCheckItem({ text: "COVID-19 pandemic response", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "46. Joe Biden",
          note: "2021–2025 · Infrastructure law; Ukraine aid; oldest president; did not seek re-election",
          planned: new CalendarDate(1942, 11, 20),
          status: "complete",
          checks: [
            newCheckItem({ text: "Infrastructure Investment and Jobs Act", ticked: true }),
            newCheckItem({ text: "Supported Ukraine against Russian invasion", ticked: true }),
            newCheckItem({ text: "Declined to seek second term", ticked: true }),
          ],
        }),
        newTodoItem({
          title: "47. Donald Trump",
          note: "2025– · Second non-consecutive term; tariffs and federal restructuring",
          planned: new CalendarDate(1946, 6, 14),
          checks: [
            newCheckItem({ text: "Broad tariff regime introduced", ticked: true }),
            newCheckItem({ text: "DOGE federal workforce reductions", ticked: true }),
            newCheckItem({ text: "Withdrew from Paris Climate Agreement again", ticked: true }),
            newCheckItem({ text: "US-Israel war on Iran" }),
          ],
        }),
      ],
    }),
    newProjectItem({
      name: "World Atlas",
      note: "Countries, capitals, and oceans — stress test",
      rows: [
        newGroupingItem({ label: "Countries of the World" }),
        ...(
          [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
          ] as const
        ).map((c) => newTodoItem({ title: c })),

        newGroupingItem({ label: "World Capitals" }),
        ...(
          [
            ["Kabul", "Afghanistan"],
            ["Tirana", "Albania"],
            ["Algiers", "Algeria"],
            ["Andorra la Vella", "Andorra"],
            ["Luanda", "Angola"],
            ["Buenos Aires", "Argentina"],
            ["Yerevan", "Armenia"],
            ["Canberra", "Australia"],
            ["Vienna", "Austria"],
            ["Baku", "Azerbaijan"],
            ["Nassau", "Bahamas"],
            ["Manama", "Bahrain"],
            ["Dhaka", "Bangladesh"],
            ["Bridgetown", "Barbados"],
            ["Minsk", "Belarus"],
            ["Brussels", "Belgium"],
            ["Belmopan", "Belize"],
            ["Porto-Novo", "Benin"],
            ["Thimphu", "Bhutan"],
            ["Sucre", "Bolivia"],
            ["Sarajevo", "Bosnia and Herzegovina"],
            ["Gaborone", "Botswana"],
            ["Brasília", "Brazil"],
            ["Bandar Seri Begawan", "Brunei"],
            ["Sofia", "Bulgaria"],
            ["Ouagadougou", "Burkina Faso"],
            ["Gitega", "Burundi"],
            ["Praia", "Cabo Verde"],
            ["Phnom Penh", "Cambodia"],
            ["Yaoundé", "Cameroon"],
            ["Ottawa", "Canada"],
            ["Bangui", "Central African Republic"],
            ["N'Djamena", "Chad"],
            ["Santiago", "Chile"],
            ["Beijing", "China"],
            ["Bogotá", "Colombia"],
            ["Moroni", "Comoros"],
            ["Brazzaville", "Congo"],
            ["San José", "Costa Rica"],
            ["Zagreb", "Croatia"],
            ["Havana", "Cuba"],
            ["Nicosia", "Cyprus"],
            ["Prague", "Czech Republic"],
            ["Copenhagen", "Denmark"],
            ["Djibouti City", "Djibouti"],
            ["Roseau", "Dominica"],
            ["Santo Domingo", "Dominican Republic"],
            ["Quito", "Ecuador"],
            ["Cairo", "Egypt"],
            ["San Salvador", "El Salvador"],
            ["Malabo", "Equatorial Guinea"],
            ["Asmara", "Eritrea"],
            ["Tallinn", "Estonia"],
            ["Mbabane", "Eswatini"],
            ["Addis Ababa", "Ethiopia"],
            ["Suva", "Fiji"],
            ["Helsinki", "Finland"],
            ["Paris", "France"],
            ["Libreville", "Gabon"],
            ["Banjul", "Gambia"],
            ["Tbilisi", "Georgia"],
            ["Berlin", "Germany"],
            ["Accra", "Ghana"],
            ["Athens", "Greece"],
            ["St. George's", "Grenada"],
            ["Guatemala City", "Guatemala"],
            ["Conakry", "Guinea"],
            ["Bissau", "Guinea-Bissau"],
            ["Georgetown", "Guyana"],
            ["Port-au-Prince", "Haiti"],
            ["Tegucigalpa", "Honduras"],
            ["Budapest", "Hungary"],
            ["Reykjavik", "Iceland"],
            ["New Delhi", "India"],
            ["Jakarta", "Indonesia"],
            ["Tehran", "Iran"],
            ["Baghdad", "Iraq"],
            ["Dublin", "Ireland"],
            ["Jerusalem", "Israel"],
            ["Rome", "Italy"],
            ["Kingston", "Jamaica"],
            ["Tokyo", "Japan"],
            ["Amman", "Jordan"],
            ["Nur-Sultan", "Kazakhstan"],
            ["Nairobi", "Kenya"],
            ["South Tarawa", "Kiribati"],
            ["Kuwait City", "Kuwait"],
            ["Bishkek", "Kyrgyzstan"],
            ["Vientiane", "Laos"],
            ["Riga", "Latvia"],
            ["Beirut", "Lebanon"],
            ["Maseru", "Lesotho"],
            ["Monrovia", "Liberia"],
            ["Tripoli", "Libya"],
            ["Vaduz", "Liechtenstein"],
            ["Vilnius", "Lithuania"],
            ["Luxembourg City", "Luxembourg"],
          ] as const
        ).map(([capital, country]) =>
          newTodoItem({ title: capital, note: `Capital of ${country}` }),
        ),

        newGroupingItem({ label: "Oceans, Seas & Major Lakes" }),
        ...(
          [
            ["Pacific Ocean", "Largest ocean; covers ~46% of Earth's water surface"],
            ["Atlantic Ocean", "Second largest; separates Americas from Europe and Africa"],
            ["Indian Ocean", "Third largest; warm and bounded by Asia, Africa, Australia"],
            ["Southern Ocean", "Surrounds Antarctica; recognized as fifth ocean in 2000"],
            ["Arctic Ocean", "Smallest and shallowest ocean; largely ice-covered"],
            ["South China Sea", "Highly contested; busiest shipping lane in the world"],
            ["Caribbean Sea", "Warm tropical sea; ~2.75 million km²"],
            ["Mediterranean Sea", "Nearly landlocked; cradle of Western civilization"],
            ["Bering Sea", "Separates Alaska from Russia; critical salmon fishery"],
            ["Gulf of Mexico", "Partially enclosed sea; site of Deepwater Horizon spill"],
            ["Sea of Japan", "Between Japan and the Korean Peninsula"],
            ["Hudson Bay", "Vast inland sea in northern Canada"],
            ["East China Sea", "Between China, Japan, and Korea"],
            ["Andaman Sea", "Part of Indian Ocean; borders Myanmar and Thailand"],
            ["North Sea", "Between UK and continental Europe; major oil field"],
            ["Red Sea", "Connects to Suez Canal; high salinity and coral reefs"],
            ["Baltic Sea", "Brackish sea; nearly enclosed by Scandinavian countries"],
            ["Caspian Sea", "World's largest lake by area; landlocked"],
            ["Persian Gulf", "Bordered by oil-rich nations; shallow and warm"],
            ["Gulf of Guinea", "Off West Africa; rich in offshore oil"],
            ["Arabian Sea", "Northwestern arm of Indian Ocean"],
            ["Coral Sea", "Off northeastern Australia; home to Great Barrier Reef"],
            ["Tasman Sea", "Between Australia and New Zealand"],
            ["Labrador Sea", "Between Labrador and Greenland; cold and stormy"],
            ["Ross Sea", "Antarctic sea; one of most pristine ocean areas"],
            ["Weddell Sea", "Antarctic sea; nearly year-round sea ice"],
            ["Barents Sea", "Arctic sea north of Norway and Russia"],
            ["Kara Sea", "Siberian Arctic sea; heavy ice cover"],
            ["Laptev Sea", "Remote Arctic sea; feeds much Arctic sea ice"],
            ["East Siberian Sea", "Shallowest Arctic sea; very remote"],
            ["Chukchi Sea", "Between Alaska and Russia above the Bering Strait"],
            ["Beaufort Sea", "North of Alaska and Canada; permanent ice pack"],
            ["Gulf of California", "Between Baja California and mainland Mexico"],
            ["Gulf of Thailand", "Shallow sea in Southeast Asia"],
            ["Timor Sea", "Between Australia and Timor-Leste"],
            ["Arafura Sea", "Between Australia and New Guinea"],
            ["Banda Sea", "Deep sea in the Maluku Islands, Indonesia"],
            ["Celebes Sea", "Between Philippines and Indonesia"],
            ["Sulu Sea", "Surrounded by Philippines islands"],
            ["Java Sea", "Shallow sea north of Java"],
            ["Molucca Sea", "East of Sulawesi, Indonesia"],
            ["Flores Sea", "Between Flores and Sulawesi, Indonesia"],
            ["Bismarck Sea", "North of Papua New Guinea"],
            ["Solomon Sea", "Between Papua New Guinea and Solomon Islands"],
            ["Philippine Sea", "Large sea east of the Philippines"],
            ["Lake Superior", "Largest of the Great Lakes by surface area"],
            ["Lake Victoria", "Largest lake in Africa; source of White Nile"],
            ["Lake Huron", "Second largest Great Lake"],
            ["Lake Michigan", "Only Great Lake entirely within the United States"],
            ["Lake Tanganyika", "Second deepest lake in the world"],
            ["Lake Baikal", "Deepest lake on Earth; holds 20% of world's fresh water"],
            ["Lake Malawi", "African Rift Valley lake; extraordinary fish diversity"],
            ["Lake Erie", "Shallowest and most southern Great Lake"],
            ["Lake Ontario", "Smallest Great Lake by surface area"],
            ["Lake Ladoga", "Largest lake in Europe; in northwestern Russia"],
            ["Lake Onega", "Second largest lake in Europe"],
            ["Lake Volta", "Largest artificial lake by surface area"],
            ["Lake Turkana", "World's largest permanent desert lake"],
            ["Lake Albert", "Shared by Uganda and DR Congo"],
            ["Lake Balkhash", "Partially freshwater, partially saline; Kazakhstan"],
            ["Lake Chad", "Shrinking lake at junction of four African countries"],
            ["Lake Titicaca", "Highest navigable lake; on Bolivia-Peru border"],
            ["Lake Nicaragua", "Largest lake in Central America"],
            ["Lake Atitlán", "Volcanic caldera lake in Guatemala"],
            ["Dead Sea", "Saltiest large water body; lowest point on Earth's surface"],
            ["Aral Sea", "Once fourth largest lake; nearly gone due to irrigation"],
            ["Lake Winnebago", "Largest lake in Wisconsin, USA"],
            ["Great Salt Lake", "Remnant of ancient Lake Bonneville in Utah"],
            ["Lake Champlain", "Shared by New York, Vermont, and Quebec"],
            ["Lake Tahoe", "Deep alpine lake on California-Nevada border"],
            ["Lake Powell", "Reservoir on Colorado River"],
            ["Lake Mead", "Largest US reservoir by volume"],
            ["Mono Lake", "Ancient saline lake in California"],
            ["Lake Issyk-Kul", "Deepest lake in Central Asia; Kyrgyzstan"],
            ["Tónlé Sap", "Largest freshwater lake in Southeast Asia"],
            ["Lake Dongting", "Second largest freshwater lake in China"],
            ["Lake Poyang", "Largest freshwater lake in China"],
            ["Lake Inle", "Highland lake in Myanmar; floating gardens"],
            ["Lake Toba", "Supervolcanic caldera lake in Sumatra"],
            ["Lake Eyre", "Australia's largest lake; usually dry salt flat"],
            ["Crater Lake", "Deepest lake in the USA; in an extinct volcano"],
            ["Lake Winnipeg", "Large shallow lake in Manitoba, Canada"],
            ["Lake Athabasca", "In the boreal forest of Alberta and Saskatchewan"],
            ["Great Bear Lake", "Largest lake entirely in Canada"],
            ["Great Slave Lake", "Deepest lake in North America"],
            ["Reindeer Lake", "On the Saskatchewan-Manitoba border"],
            ["Lake Nipigon", "Largest lake entirely in Ontario"],
            ["Lake of the Woods", "Shared by Minnesota, Ontario, and Manitoba"],
            ["Lake Simcoe", "Important lake in southern Ontario"],
            ["Flathead Lake", "Largest natural freshwater lake in the western US"],
            ["Upper Klamath Lake", "Largest lake in Oregon"],
            ["Lake Okeechobee", "Largest lake in Florida"],
            ["Lake Pontchartrain", "Shallow brackish estuary in Louisiana"],
            ["Chesapeake Bay", "Largest estuary in the United States"],
            ["San Francisco Bay", "Major Pacific estuary in California"],
            ["Puget Sound", "Deep fjord-like inlet in Washington State"],
            ["Cook Inlet", "Tidal inlet in Alaska near Anchorage"],
            ["Prince William Sound", "Glacially carved sound in southern Alaska"],
            ["Glacier Bay", "UNESCO World Heritage site in Alaska"],
            ["Lake George", "Called 'Queen of American Lakes' in New York"],
            ["Finger Lakes", "Group of long narrow lakes in upstate New York"],
            ["Lake Oneida", "Largest lake entirely within New York State"],
          ] as const
        ).map(([name, note]) => newTodoItem({ title: name, note })),
      ],
    }),
  ]);

// important to wire the projects returned from $state to panel's instance, so it actually controls it globally.
export const mockPanels = (projects: ProjectItem[]): PanelItem[] => {
  return [
    newPanelItem({
      id: `${GUEST_ID_PREFIX}panel-main`,
      instance: newProjectInstance({
        project: projects[0],
        todoExpanded: { [projects[0].rows[2].id]: true },
      }),
      layout: { sideShow: true, sideWidth: 200, spacerLeft: "disabled" },
    }),
  ];
};
